services:
  server:
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - 'vaultwarden:/data/'
    networks:
      docker-intern:
        ipv4_address: 172.18.0.20
    ports:
      - '6081:80'
      - '6022:3012'
    image: 'vaultwarden/server:latest'

    environment:
      - TZ=Europe/Zurich
      - DATABASE_URL=
      - ICON_CACHE_TTL=
      - ICON_CACHE_NEGTTL=
      - WEB_VAULT_FOLDER=
      - WEB_VAULT_ENABLED=
      - WEBSOCKET_ENABLED=
      - SENDS_ALLOWED=
      - EMERGENCY_ACCESS_ALLOWED=
      - EVENTS_DAYS_RETAIN=
      - SIGNUPS_ALLOWED=
      - SIGNUPS_VERIFY=f
      - SIGNUPS_VERIFY_RESEND_TIME=
      - SIGNUPS_VERIFY_RESEND_LIMIT=
      - INVITATION_ORG_NAME=
      - ORG_ATTACHMENT_LIMIT=
      - USER_ATTACHMENT_LIMIT=
      - TRASH_AUTO_DELETE_DAYS=
      - PASSWORD_ITERATIONS=
      - DOMAIN=
      - ADMIN_TOKEN=
      - SMTP_HOST=
      - SMTP_FROM=
      - SMTP_FROM_NAME=
      - SMTP_SECURITY=
      - SMTP_PORT=4
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - SMTP_TIMEOUT=
      - SMTP_AUTH_MECHANISM=
      - HELO_NAME=
      - REQUIRE_DEVICE_EMAIL=


volumes:
  vaultwarden:

networks:
  docker-intern:
    external: true
    name: docker-intern
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1