services:
  semaphore-mysql:
    restart: unless-stopped
    image: mysql:8.0
    hostname: semaphore-mysql
    container_name: semaphore-db
    networks:
      - traefik_default
    volumes:
      - ${semaphore_mysql}:/var/lib/mysql

    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PW}
  semaphore:
    restart: unless-stopped
    image: semaphoreui/semaphore:latest
    container_name: semaphore-ui
    networks:
      - traefik_default
    volumes:
      - ~/.ssh:/root/.ssh
      - ${semaphore_data}:/etc/semaphore
      - ${semaphore_playbooks}:/etc/playbooks
    environment:
      SEMAPHORE_DB_USER: ${DB_USER}
      SEMAPHORE_DB_PASS: ${DB_PW}
      SEMAPHORE_DB_HOST: semaphore-mysql
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: ${DB_NAME}
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN}
      SEMAPHORE_ADMIN_NAME: ${ADM_USER}
      SEMAPHORE_ADMIN_EMAIL: ${ADM_MAIL}
      SEMAPHORE_ADMIN: ${ADM_USER}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${SEMAPHORE_ACCESS_KEY}

    depends_on:
      - semaphore-mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=web"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_NAME}.${DOMAIN}`)"
      - "traefik.http.middlewares.${SERVICE_NAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=${SERVICE_NAME}-https-redirect"
      - "traefik.http.routers.${SERVICE_NAME}-secure.entrypoints=websecure"
      - "traefik.http.routers.${SERVICE_NAME}-secure.rule=Host(`${SERVICE_NAME}.${DOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}-secure.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}-secure.service=${SERVICE_NAME}"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${SERVICE_PORT}"
      - "traefik.http.routers.${SERVICE_NAME}-secure.tls.certresolver=production"
      - "traefik.docker.network=traefik_default"
networks:
  traefik_default:
    external: true